# Site settings
title: Daniel Münch
description: 'Neuroscientist'
url: 'https://muench.bio'
baseurl: 'https://muench.bio/'
google_analytics: 'UA-12714453-10'
disqus_shortname: 'danielmuench'
timezone: Europe/Berlin

author:
  name: 'Daniel Münch'
  email: daniel@muench.bio
  twitter_username: dahaniel
#  facebook_username: DahanielDahanielDahanielDahanielDahanielDahaniel
  github_username:  dahaniel
  linkedin_username:  danielmuench
  mastodon:
    mastodon_username: dahaniel
    mastodon_instance: scholar.social

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge


# kramdown:
#   extensions:
#     - footnotes
#     - hard_wrap
#     - no_intra_emphasis
#     - autolink
#     - strikethrough

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
